[bot]
# Boolean to tell if the bot is under maintenance or not
maintenance = false
# Boolean to tell if the bot is under test mode
test_mode = false

[mqtt]
# The MQTT server host
host = "mqtt://127.0.0.1"

[database]
# Database name prefix
prefix = ""
# The host (ip or DNS) of the database
host = "127.0.0.1"
# The port of the database
port = 3306
# The user of the database
user = "draftbot"
# The password of a database user.
password = "secret_password"
# The root password, used to create the databases
root_password = "super_secret_password"


[discord_bot_list]
# Put the port of the DBL Webhook
webhook_port = 0
# Put the url of the DBL Webhook. Choose a challenging URL to avoid it being found
webhook_url = "/secret_url"
# Put the id of the role won by a vote on DBL
vote_role_id = ""
# Put the channel id of the vote logs
channel_id = ""
# Put the DBL server token
token = ""


[backups]
# Enabled backups. May contain LOCAL and DROPBOX and must be separated with commas (e.g., LOCAL, DROPBOX)
enabled = ""
# Zip backup archive password
archive_password = ""
# The dropbox token used to back up the database
dropbox_token = ""


[others]
# The API key for the nasa API
nasa_api_key = ""