version = 1

exclude_patterns = [
    "Core/src/core/utils/astronomy.ts",
    "Core/src/core/database/game/migrations/*.ts",
    "Core/src/core/database/logs/migrations/*.ts"
]

[[analyzers]]
name = "javascript"
enabled = true
dependency_file_paths = [
    "Core",
    "Discord",
    "Lib"
]

[analyzers.meta]
skip_doc_coverage = ["class-expression"]