version = 1

exclude_patterns = [
    "Core/src/core/utils/astronomy.ts",
    "Core/src/core/database/game/migrations/*.ts",
    "Core/src/core/database/logs/migrations/*.ts",
	"**/__tests__/**",
	"**/tests/**",
	"**/vitest.setup.ts"
]

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
skip_doc_coverage = ["class-expression", "class-declaration"]