export abstract class BlockingConstants {
	static readonly REASONS = {
		ACCEPT_ITEM: "acceptItem",
		CHIEF_GUILD_LEAVE: "chiefGuildLeave",
		CHOOSE_DESTINATION: "chooseDestination",
		CLASS: "class",
		DAILY_BONUS: "dailyBonus",
		DEPOSIT: "deposit",
		DRINK: "drink",
		FIGHT: "fight",
		FIGHT_CONFIRMATION: "fightConfirmation",
		GOBLET_CHOOSE: "gobletChoose",
		WITCH_CHOOSE: "witchChoose",
		FIGHT_PET_CHOOSE: "fightPetChoose",
		GUILD_ADD: "guildInvite",
		GUILD_CREATE: "guildCreate",
		GUILD_DESCRIPTION: "guildDescription",
		GUILD_ELDER: "guildElder",
		GUILD_ELDER_REMOVE: "guildElderRemove",
		GUILD_KICK: "guildKick",
		GUILD_LEAVE: "guildLeave",
		GUILD_SHOP: "guildShop",
		GUILD_SHOP_CONFIRMATION: "guildShopConfirmation",
		LOTTERY: "lottery",
		MERCHANT: "merchant",
		MISSION_SHOP: "missionShop",
		MISSION_SHOP_CONFIRMATION: "missionShopConfirmation",
		NONE: "none",
		PET_FEED: "petFeed",
		PET_FREE: "petFree",
		PET_SELL: "petSell",
		PET_SELL_CONFIRM: "petSellConfirm",
		PET_TRANSFER: "petTransfer",
		PET_EXPEDITION: "petExpedition",
		PET_EXPEDITION_CHOICE: "petExpeditionChoice",
		PVE_ISLAND: "pveIsland",
		REPORT: "report",
		SELL: "sell",
		SELL_CONFIRM: "sellConfirm",
		SHOP: "shop",
		SHOP_CONFIRMATION: "shopConfirmation",
		SWITCH: "switch",
		TEST: "test",
		UNLOCK: "unlock",
		START_BOSS_FIGHT: "startBossFight",
		REPORT_COMMAND: "reportCommand",
		REPORT_USE_TOKENS: "reportUseTokens",
		REPORT_BUY_HEAL: "reportBuyHeal",
		CART_SMALL_EVENT: "cartSmallEvent",
		LIMOGES_SMALL_EVENT: "limogesSmallEvent",
		PET_FOOD_SMALL_EVENT: "petFoodSmallEvent",
		BAD_PET_SMALL_EVENT: "badPetSmallEvent",
		SKIP_MISSION: "skipMission",
		SLOT_EXTENSION: "slotExtension"
	} as const;
}

export type BlockingReason = (typeof BlockingConstants.REASONS)[keyof typeof BlockingConstants.REASONS];
