export const FightAlterations = {
	BLEEDING: "bleeding",
	BLIND: "blind",
	BURNED: "burned",
	ALLIES_ARE_PRESENT: "alliesArePresent",
	CONCENTRATED: "concentrated",
	CONFUSED: "confused",
	CURSED: "cursed",
	DIRTY: "dirty",
	FROZEN: "frozen",
	FULL: "full",
	IRRADIATED: "irradiated",
	OUTRAGE: "outrage",
	PARALYZED: "paralyzed",
	PETRIFIED: "petrified",
	POISONED: "poisoned",
	PROTECTED: "protected",
	SLOWED: "slowed",
	SOAKED: "soaked",
	STUNNED: "stunned",
	SUBMERGED: "submerged",
	SWALLOWED: "swallowed",
	TARGETED: "targeted",
	WEAK: "weak"
};
