name: Core Module Tests
on:
  pull_request:
    branches:
      - '**'
    paths:
      - Core/**
  push:
    branches:
      - develop
      - master
    paths:
      - Core/**
  workflow_dispatch:

jobs:
  test-core-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version stable

      # Cache Yarn dependencies for Core module
      - name: Cache Core dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./Core/.yarn/cache  
            ./Core/.pnp.cjs
          key: ${{ runner.os }}-core-dependencies-${{ hashFiles('./Core/yarn.lock') }}

      - name: Install dependencies and Run Tests in Core folder
        working-directory: ./Core
        run: |
          yarn install
          yarn test

      - name: Run Test Coverage in Core folder
        working-directory: ./Core
        run: |
          yarn test:coverage