name: Core module

on:
  pull_request:
    branches: 
      - draftbot-v5
    paths:
      - Core/**

jobs:
  eslint-core-module:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment once for all jobs
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Repeat the caching step and ESLint check for the Core subproject
      - name: Cache Core dependencies
        uses: actions/cache@v3
        with:
          path: ./Core/node_modules
          key: ${{ runner.os }}-core-dependencies-${{ hashFiles('./Core/yarn.lock') }}

      - name: Install dependencies and Run ESLint in Core folder
        working-directory: ./Core
        run: |
          yarn install    
          yarn eslint
