name: Discord Module Tests
on:
  pull_request:
    branches:
      - '**'
    paths:
      - Discord/**
  push:
    branches:
      - develop
      - master
    paths:
      - Discord/**
  workflow_dispatch:

jobs:
  test-discord-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      # Setup Yarn
      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version stable

      # Cache Yarn dependencies for Discord module
      - name: Cache Discord dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./Discord/.yarn/cache  
            ./Discord/.pnp.cjs
          key: ${{ runner.os }}-discord-dependencies-${{ hashFiles('./Discord/yarn.lock') }}

      - name: Install dependencies and Run Tests in Discord folder
        working-directory: ./Discord
        run: |
          yarn install
          # Add the Vitest commands to Discord module's package.json
          yarn add --dev vitest @vitest/coverage-v8
          echo '{ "scripts": { "test": "vitest run", "test:watch": "vitest", "test:coverage": "vitest run --coverage" } }' > .vitest-scripts.json
          npx json -f package.json -I -e "this.scripts=Object.assign(this.scripts, require('./.vitest-scripts.json').scripts)"
          yarn test