name: Docker Images Pre Release CI

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Get current date
      id: date
      run: echo "date=$(date +'%s')" >> $GITHUB_OUTPUT
    -
      name: Build and push Core
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Core/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/core-pre-release:latest,${{ secrets.DOCKER_HUB_USERNAME }}/core-pre-release:${{ steps.date.outputs.date }}
    -
      name: Build and push Discord
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Discord/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/discord-pre-release:latest,${{ secrets.DOCKER_HUB_USERNAME }}/discord-pre-release:${{ steps.date.outputs.date }}