name: Lib Module Tests
on:
  pull_request:
    branches:
      - '**'
    paths:
      - Lib/**
  push:
    branches:
      - develop
      - master
    paths:
      - Lib/**
  workflow_dispatch:

jobs:
  test-lib-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      # Setup Yarn stable
      - name: Setup Yarn
        run: |
          corepack enable
          yarn set version stable

      # Cache Yarn dependencies
      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./Lib/.yarn/cache  
            ./Lib/.pnp.cjs
          key: ${{ runner.os }}-yarn-${{ hashFiles('./Lib/yarn.lock') }}

      - name: Install dependencies and Setup Vitest in Lib folder
        working-directory: ./Lib
        run: |
          yarn install
          # Add Vitest to the Lib module
          yarn add --dev vitest @vitest/coverage-v8
          echo '{ "scripts": { "test": "vitest run", "test:watch": "vitest", "test:coverage": "vitest run --coverage" } }' > .vitest-scripts.json
          npx json -f package.json -I -e "this.scripts=Object.assign(this.scripts, require('./.vitest-scripts.json').scripts)"
          yarn test